### PR TITLE
Lucky Numbers concept exercise

### PR DESCRIPTION
**Pull request by mk-mxp**
I prepared the Lucky Numbers concept exercise for concept `type-juggling`. It is limited to `int` and `string` conversions to keep it small and focused.

I had no access to the forum, yet, to ask my questions about the introduction template and `config.json` (will do that tomorrow). And before writing up `hints.md` I'd like to get feedback on the exercise.

### CODE REVIEW

**Comment by mk-mxp** [comment]
I think, configlet doesn't like me working a branch...

**Comment by neenjaw** [comment]
> I think, configlet doesn't like me working on a branch...

Yea this CI action has trouble pushing the "generated" commit to a fork branch.  I would encourage you to get configlet running locally and then generate and commit the result.  Then you can use the CI action as a sort of "check" to make sure that it was generated correctly and all the sources are consistent.

**Comment by neenjaw** [comment]
If you have the repo forked, you can run `./bin/fetch-configlet` and it will get the newest version appropriate to your architecture

**Review by neenjaw — COMMENTED** [review]
Exercise looks good in this first draft, agree this seems like a good exercise for this concept

**Comment by mk-mxp** [comment]
> If you have the repo forked, you can run `./bin/fetch-configlet` and it will get the newest version appropriate to your architecture

Worked like a charm, and now the introduction is generated and commited. Adding the hints...

**Review by neenjaw — APPROVED** [review]
:shipit: Nice work here, great first cut

**Pull request merged**
