### PR TITLE
Update make file dependencies

### PR DESCRIPTION
**Pull request by petemcfarlane**
Including PHPUnit 9 and probably CodeSniffer

This is a work in progress...

### CODE REVIEW

**Comment by neenjaw** [comment]
@petemcfarlane, how far is this along? What work is left to do on it?

**Comment by petemcfarlane** [comment]
Sorry @neenjaw the work was almost 10 months ago, I can’t remember what the state is or why it was stopped. If #320 is ready I recommend merging that then closing this PR. Perhaps one or two of the commits could be cherrypicked if still relevant?

**Comment by neenjaw** [comment]
At the very least I think this serves as a good template for what needs to be done to bring things up to PHP 9.

As per your recommendation, will likely merge #320 then close this +/- cherrypick commits

**Comment by neenjaw** [comment]
I think this is now superseded by #341. Should it be closed?

**Pull request closed without merging**
