### PR TITLE
Adds the two-fer problem.

### PR DESCRIPTION
**Pull request by rossbearman**
This implements the two-fer problem, primarily so it can be used to begin testing a PHP analyser for [Exercism's automated mentoring support project](https://github.com/exercism/automated-mentoring-support).

### CODE REVIEW

**Comment by dstockto** [comment]
This looks good to me. 👍 I don't know if it needs to have something about what exercise unlocks it, but the code, test and instructions all look good.

**Comment by petemcfarlane** [comment]
Cool! Are you going to open an issue to create a PHP analyser repo then?

**Comment by rossbearman** [comment]
@G-Rath is possibly looking into making one for PHP, although he's tackling TypeScript and JavaScript first. I just thought I'd get two-fer in the track so that it can be picked up whenever someone has time to look at it.

**Comment by petemcfarlane** [comment]
Cool, I'd be keen to see how it develops!

**Pull request merged**
