### PR TITLE
#48in24: Meetup 2024-08-20 and PHP is a featured language

### PR DESCRIPTION
**Pull request by sarad1p1ty**
As per exercism#667:

Meetup will be the only exercise with PHP as featured language during #48in24! Let's prepare it well:

- [x] Run 'bin/configlet sync -u -e meetup --yes --docs --filepaths --metadata --tests include' (updates the Markdown files and maybe 'tests.toml')
  - docs: instructions unsynced: meetup
  - metadata: unsynced: meetup
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (uuid / @testdox in DocBlocks)
- [ ] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

In addition to the other sync-ing tasks, consider doing these:

- [ ] Polish the tests to be really readable (e.g. add failure messages to assertions)
- [ ] https://github.com/exercism/php/issues/617
- [ ] Go through the track docs and update installation instructions, help resources etc.
- [ ] Add [approaches](https://exercism.org/docs/building/tracks/approaches) and [articles](https://exercism.org/docs/building/tracks/articles)

### CODE REVIEW

**Comment by mk-mxp** [comment]
Looks like there is a problem with an exercise you did not change... Could you change this line in `composer.json`:

```json
    "phpunit/phpunit": "^10.5",
```

to this:

```json
    "phpunit/phpunit": "^10.5 <10.5.30",
```

and commit / push that? That version has changed against the last successful CI run. It's a workaround for now, not the solution.

**Comment by mk-mxp** [comment]
@sarad1p1ty I solved the problem now. Please rebase this PR on the latest `main`, CI should pass then.

**Comment by sarad1p1ty** [comment]
Thank you for that. Hopefully all good now.

Apart from adding DocBlocks, the basic tasks were mostly already done :)

I'd like to neated up the test code, but wanted to run the format by you first, eg:

```
/**
     * uuid: d7f8eadd-d4fc-46ee-8a20-e97bd3fd01c8
     * @testdox when teenth Monday is the 13th, the first day of the teenth week
     */
    public function testMonteenthOfMay2013(): void
    {
        $expected = new DateTimeImmutable("2013/5/13");
        $actual = meetup_day(2013, 5, "teenth", "Monday");
        $message = "Your function did not return the correct date.";
        $this->assertEquals($expected, $actual, $message);
    }
```


Something like that?

**Comment by sarad1p1ty** [comment]
I'm also not quite sure how to action https://github.com/exercism/php/issues/617 ?

**Comment by mk-mxp** [comment]
@sarad1p1ty Thank you for updating the branch. I think you cannot quickly solve #617 or one of the other possible action points. Those were meant for a long term preparation - which didn't happen.

> ```
>         $message = "Your function did not return the correct date.";
> ```

I wouldn't do that. That is the obvious reason for failing tests. I think I wrote that action suggestion after facing some complicated, hard to understand tests in another exercise. It doesn't make sense now, after looking at all the actual tests.

The other changes look good, with 2 additional spacing lines to make the Arrange, Act, Assert pattern stand out:

```php
    {
        $expected = new DateTimeImmutable("2013/5/13");

        $actual = meetup_day(2013, 5, "teenth", "Monday");

        $this->assertEquals($expected, $actual);
    }
```

**Review by mk-mxp — APPROVED** [review]
I'll merge this in the evening. We may add the structural changes later, too.

Thanks a lot for your contribution!

**Comment by sarad1p1ty** [comment]
Thank you for your help. 
Sorry, I messed up the git rebase. I'm going to quit now while I still can.

**Review by mk-mxp — APPROVED** [review]
I don't know what kind of git trouble you are facing...this PR looks great. Thank you very much!

**Pull request merged**
