### PR TITLE
Add union types concept

### PR DESCRIPTION
**Pull request by dstockto**
Attn: @neenjaw  - Is this kind of what you're looking for for moving the stuff over from that branch? I took the liberty of expanding the concept. Hopefully that's ok.

Are these supposed to be linked together in a graph and have corresponding exercises? Does that come later when more of these are moved over?

### CODE REVIEW

**Comment by neenjaw** [comment]
So there are a bunch of empty ones on that branch which are probably more the focus of my concern. So how these concepts work is that the `introduction.md` is intentionally minimal -- it is the minimum required to get a foothold on the concept. So it doesn't provide mastery over that concept.  The `about.md` can be more detailed and provide a fuller context. 

If you want to take on any of the incompleted concepts, my plan was to create a full complement of concepts there then merge them on to the main branch at once.

Concepts don't form a graph on their own, they have a graph formed indirectly by learning exercises that teach and prerequisite them.

The grand plan is to:
- finish a rough draft of the identified set of concepts
- merge them to the main branch
- start creating concept exercises (probably looking at csharp as a prototype since they are similar-ish languages)

--- 

So for this PR, if you could:
- point it at the concepts branch
- remove the additions to the introduction file, if there are edits to do there, please feel free then can review them when you think its ready
- add the detail to the `about.md` file to provide the in depth discussion on the concept

---

Does that sound reasonable?

**Comment by dstockto** [comment]
I think that makes sense - it may take me a few more back-and-forths to get to what you're looking for but I think I get it better now. I'll see what I can figure out with this one later and then look at some blanks.

**Comment by neenjaw** [comment]
Oh, I've been working from the bottom up on that list of concepts, if you want to start top-down then we minimize chance of collision

**Comment by dstockto** [comment]
Do you mean alphabetically or is there another list with a particular order that you're following?

**Comment by neenjaw** [comment]
alphabetically by concept folder name

**Pull request closed without merging**
