### PR TITLE
fix config for configlet

### PR DESCRIPTION
**Pull request by neenjaw**

### CODE REVIEW

**Comment by neenjaw** [comment]
@ErikSchierboom, @exercism/reviewers, could you approve please?

**Comment by BethanyG** [comment]
I'm in reviewers, but can't review here. 😢

**Review by BethanyG — APPROVED** [review]
LGTM!  🌟

**Review by hiljusti — APPROVED** [review]

**Comment by hiljusti** [comment]
> I'm in reviewers, but can't meaningfully review here. cry @iHiD -- do reviewers need to be explicitly added, or are my permissions just funky?

Same for me. Not sure with GitHub, but anyone know if it's possible for repo settings to require PR review from reviewers with write access _or_ exercism/reviewers?

**Comment by neenjaw** [comment]
Yes, if it doesn't work for one, it won't work for any. I had thought it was added to this repo, but I guess not at this time.  @iHiD can look at this tomorrow, there's no real rush

**Comment by hiljusti** [comment]
I'm more than happy to look at this or other PHP changes after that

**Comment by neenjaw** [comment]
Cool, I am looking for some help with something for this track.  On the `concepts` branch in the `concepts` folder @djjohnsongeek and I have stubbed concepts to be written out.  They are all topic from php.net's documentation that I'd like to prepare to just plug exercises into when I get around to concept exercises for this track.  If you are interested in writing up one or two, that'd be a great help.  I'm working my way up from z->a alphabetically

**Comment by iHiD** [comment]
Reviewers wasn't added - I've added it now.

**Pull request merged**
