### PR TITLE
Improve example in introduction.md

### PR DESCRIPTION
**Pull request by aan-t**
A part of the example didn't make too much sense and a comment was misplaced

### CODE REVIEW

**Review by neenjaw — APPROVED** [review]

**Comment by neenjaw** [comment]
Thanks

**Review by neenjaw — COMMENTED** [review]
@aan-t Can you also update the source files for this generated file? 

sources:
- https://github.com/exercism/php/blob/main/concepts/arrays/about.md
- https://github.com/exercism/php/blob/main/concepts/arrays/introduction.md

**Comment by aan-t** [comment]
Sure, will create a new PR with those changes included as well. (That's how it works, right? I'm still new to this)

**Comment by neenjaw** [comment]
You don’t have to close it. If you are using GitHub as an editor, you can edit the next page and select your branch to apply the changes to, Willis will update this request.

**Pull request closed without merging**
