### PR TITLE
Namespace and new directory structure for robot-name and robot-simulator

### PR DESCRIPTION
**Pull request by arueckauer**
This PR adds namespacing and the new directory structure to robot-name and robot-simulator exercises.

I would like to use this as base for required changes in the Makefile to ensure proper execution of tests and style checking.

The example solution of robot-name has two classes, which I spearated into two files. The test file is only requiring the class which will also be provided as stub file. Additional classes have to be required in the implementation itself.

I made local adjustments to Makefile to copy the `example` directory to `src`. How can the following line be translated?

```
@cat ./exercises/$(ASSIGNMENT)/$(TSTFILE) | sed '/markTestSkipped()/d' > $(OUTDIR)/$(TSTFILE)
```

Two possible solutions would be to either

- convert the assignment to PascalCase and add test or
- parse any PHP files within the test directory.

Not sure, which way to go?

### CODE REVIEW

**Comment by arueckauer** [comment]
Ping @petemcfarlane & @dstockto

**Comment by petemcfarlane** [comment]
Hi @arueckauer, sorry for the delay. I'd think that parsing any PHP files to the

**Comment by arueckauer** [comment]
Hello @petemcfarlane, that sounds good to me, yes.

Goal would be to be able to provide current functionality to run tests / style checks for an inidividual assignment or all assignments. Since I am very new to makefile, I am appreciating any help on that.

I see, you closed this PR. How would you like to proceed?

**Comment by petemcfarlane** [comment]
Sorry for accidentally closing! 🤦‍♂️

**Comment by neenjaw** [comment]
@arueckauer are you interested in completing this work? There have been some breaking changes in the directory structure and the continuous integration tests that would need some work to update.

**Comment by arueckauer** [comment]
@neenjaw As I have only been passively following the changes for v3, I am not 100 % sure of what needs to be done. It feels like it would be a good exercise to provide a new PR to gain necessary understanding of the new/changed setup which might also require less effort on the desired scope of this PR. I'll close it for now.

**Pull request closed without merging**
