### PR TITLE
Adds the Scale Generator exercise.

### PR DESCRIPTION
**Pull request by 0x647262**
Work towards integrating: https://github.com/exercism/php/pull/297

### CODE REVIEW

**Comment by 0x647262** [comment]
@neenjaw Ready for review.

By the way, I see a `tests.toml` file in come of the other folders. Is that something I need to manually generate?

**Comment by neenjaw** [comment]
At this time, we aren't using the problem-specs repo (other than for inspiration), so for now, no you don't need the `tests.toml` for this.

**Review by neenjaw — APPROVED** [review]
Exercise looks good to go, I need to merge #392 first, but this can be merged after that. :)

**Comment by petemcfarlane** [comment]
Hey is this still ready to be merged @neenjaw ?

> Exercise looks good to go, I need to merge #392 first, but this can be merged after that. :)

**Comment by neenjaw** [comment]
Yep!

**Comment by neenjaw** [comment]
Thanks for catching this @petemcfarlane, hadn't had a chance yet to catch up with the exercism backlog yet.

**Pull request merged**
