### PR TITLE
Diamond exercise for php.

### PR DESCRIPTION
**Pull request by camilopayan**

### CODE REVIEW

**Comment by camilopayan** [comment]
Ready for merge

**Comment by camilopayan** [comment]
Fixed the indentation issues.

**Comment by camilopayan** [comment]
I see there's an issue with locking and unlocking but I don't really get what that means.

**Comment by petemcfarlane** [comment]
Same issue here. You could change the `unlocked_by` in the config, or just set it to null perhaps?

**Comment by camilopayan** [comment]
Updated the `unlocked_by` to null

**Pull request merged**
