### PR TITLE
Add Go counting to PHP

### PR DESCRIPTION
**Pull request by camilopayan**

### CODE REVIEW

**Comment by neenjaw** [comment]
@camilopayan are you interested in completing this work? There have been some breaking changes in the directory structure and the continuous integration tests that would need some work to update.

**Comment by 0x647262** [comment]
@neenjaw I'll handle this one this weekend.

**Comment by NhanAZ** [comment]
> @neenjawTôi sẽ giải quyết vấn đề này vào cuối tuần này.

It's been a year... Are you still there?

**Comment by neenjaw** [comment]
Given this exercise is now severely out of date with respect to the changes that came with the current version of Exercism, I am converting this PR to draft as it is not ready for review/merge.  Will re-review at a later time, if no activity, will close.

**Comment by neenjaw** [comment]
No activity

**Pull request closed without merging**
