### PR TITLE
Sync Allergies

### PR DESCRIPTION
**Pull request by fejan-malek**
https://github.com/exercism/php/issues/761

We need to update the `testdox` and `uuid` comments in the test case.

And this exercise also contains `dataprovider` test.

### CODE REVIEW

**Comment by mk-mxp** [comment]
@fejan-malek I will take a deeper look into this. May take some days to answer.

**Comment by mk-mxp** [comment]
@fejan-malek I remember doing this exercise, and I struggled heavily with the design of the exercise. And I am not the only one: Track status says, that only 49% finished the exercise. In addition, only 82 persons finished it at all.

So we should not invest more into the current state of the exercise. I will merge the changes you already made. Maybe you want to help re-writing the exercise? See #772

**Review by mk-mxp — APPROVED** [review]
Thanks for this!

**Comment by fejan-malek** [comment]
> So we should not invest more into the current state of the exercise. I will merge the changes you already made. Maybe you want to help re-writing the exercise? See https://github.com/exercism/php/issues/772

Sure @mk-mxp Will take a look because I never contribute to developing an exercise.

**Pull request merged**
