### PR TITLE
Adds the affine cipher exercise

### PR DESCRIPTION
**Pull request by camilopayan**
Needless to say, not finished yet! Just wanted to claim the exercise.

### CODE REVIEW

**Comment by camilopayan** [comment]
All right, this PR is ready for review! I'm going to go ahead and do another problem.

**Comment by camilopayan** [comment]
Fixed the style issues! Thanks for the heads up on the `make style-check`
command.

**Comment by petemcfarlane** [comment]
Think I've worked out why the build is failing.

>The exercise 'affine-cipher' is being unlocked by a non-core exercise. Non-core exercises can only be unlocked by core exercises.

So in the config you say it's unlocked by "grains" but "grains" is not a core exercise. Could you change this to a core exercise instead? Thanks 🙂

**Comment by camilopayan** [comment]
All right, set it to null, which matches the rest, looks like.

**Pull request merged**
