### PR TITLE
Adds the High Scores exercise.

### PR DESCRIPTION
**Pull request by camilopayan**

### CODE REVIEW

**Comment by camilopayan** [comment]
Let me know how you'd like the config for High Scores to look in `config.json`. In the Javascript track, High Scores is unlocked by Pangram, but in the Ruby track High Scores is core. Is there a canonical place for this?

**Comment by neenjaw** [comment]
@camilopayan are you interested in completing this work? There have been some breaking changes in the directory structure and the continuous integration tests that would need some work to update.

**Comment by neenjaw** [comment]
In regards to your question, there will not be core exercises in v3, so you don't need to add that anymore

**Comment by MichaelBunker** [comment]
I can also bring this one up to date if it is abandoned.

**Comment by camilopayan** [comment]
Sorry about the long delay, I've been pretty swamped. Go for it @MichaelBunker I appreciate it.

**Comment by neenjaw** [comment]
Fulfilled by #398

**Pull request closed without merging**
