### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by vnkmpf**

### CODE REVIEW

**Review by neenjaw — APPROVED** [review]

**Comment by neenjaw** [comment]
I'm not sure why configlet is failing here.  It needs to pass for it to be deployed to the website.

@ErikSchierboom, any insight here when you have a chance?

**Comment by ErikSchierboom** [comment]
@neenjaw It's not configlet that's failing though:mhttps://github.com/exercism/php/actions/runs/5798376802/job/15716001411?pr=543

**Comment by neenjaw** [comment]
@ErikSchierboom ah.. it's the downstream branch name.

**Comment by vnkmpf** [comment]
> it's the downstream branch name.

Should I rename the branch and make a new PR? :)

**Comment by neenjaw** [comment]
> > it's the downstream branch name.
> 
> Should I rename the branch and make a new PR? :)

Yes please! the branch name seems to encounter a limitation in the action runner.

**Comment by vnkmpf** [comment]
Pushed in #546

**Pull request closed without merging**
