### PR TITLE
[WIP] Adds the Simple Cipher exercise

### PR DESCRIPTION
**Pull request by camilopayan**

### CODE REVIEW

**Comment by camilopayan** [comment]
Working on the solved `example.php`. For some reason I fail the cipher is reversible test with random keys, but not with any other key. I've been getting capital letters in the output, so it seems like it's going over 97, but I'm not sure how. Still working on that.

**Comment by neenjaw** [comment]
@camilopayan are you interested in completing this work? There have been some breaking changes in the directory structure and the continuous integration tests that would need some work to update.

**Comment by MichaelBunker** [comment]
I am willing to complete this work if it is abandoned.

**Comment by MichaelBunker** [comment]
This work was completed in https://github.com/exercism/php/pull/395 and https://github.com/exercism/php/pull/403 and this PR can be closed.

**Comment by SleeplessByte** [comment]
Thanks you @MichaelBunker

**Pull request closed without merging**
