### PR TITLE
Adds the Scale Generator exercise.

### PR DESCRIPTION
**Pull request by camilopayan**

### CODE REVIEW

**Comment by neenjaw** [comment]
@camilopayan are you interested in completing this work? There have been some breaking changes in the directory structure and the continuous integration tests that would need some work to update.

**Comment by 0x647262** [comment]
@neenjaw unless @camilopayan would like to finish this PR themself, I would be happy dust off this PR and bring it up to standards.

**Comment by neenjaw** [comment]
Sounds good to me.  Let's give @camilopayan a few days to respond, after that I think it's fair game.

It might be easier to copy the code to a new branch based on the current main branch to make it easier.  Make sure to credit camilopayan as a co-author. :)

**Comment by neenjaw** [comment]
@0x647262, if you want to finish this exercise I think @camilopayan has had a fair chance to response. please feel free to continue this work.

Like above, I think probably best to copy this work to a new branch that you control.  Will close this PR once you've done that

**Comment by neenjaw** [comment]
Fulfulled by #386

**Pull request closed without merging**
