### PR TITLE
Use the new PSR12 standards

### PR DESCRIPTION
**Pull request by yisraeldov**
> PSR-2 was accepted in 2012 and since then a number of changes have been made to PHP which has implications for coding style guidelines. Whilst PSR-2 is very comprehensive of PHP functionality that existed at the time of writing, new functionality is very open to interpretation. This PSR, therefore, seeks to clarify the content of PSR-2 in a more modern context with new functionality available, and make the errata to PSR-2 binding.

### CODE REVIEW

**Comment by arueckauer** [comment]
@yisraeldov Would love to see that being merged. Can I assist you in any way?

**Comment by yisraeldov** [comment]
What else is needed from me?

**Comment by petemcfarlane** [comment]
One more error
```
FILE: /home/travis/build/exercism/php/exercises/bob/bob_test.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 14 | ERROR | [x] Parentheses must be used when instantiating a new class
    |       |     (PSR12.Classes.ClassInstantiation.MissingParentheses)
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
```

**Comment by yisraeldov** [comment]
Thanks @petemcfarlane @arueckauer 

The CI stops on the first error so there will probably be another after that.

The best thing to do would to just checkout everything and run PHPCBF.

Also it is weird that the CI is checking each file individually instead of all at once, that should probably be changed.

**Comment by arueckauer** [comment]
You can run `make style-check` prior to committing/pushing.

**Comment by yisraeldov** [comment]
Obviously, but I don't have a checkout of the project right now, I have
just been making the fixes directly in github.

The CI should give all the issues, not just one and stop.

**Comment by neenjaw** [comment]
2021 update, directory structure has changed. I plan to use this as a template for the changes required to bring the track up to spec in time for the next version of exercism.  See #334 for the new WIP PR where commits can be pushed to.  Happy for your contributions if you are still interested. If not, thanks for doing this work in progress, it's a great help to get the ball rolling!! 💙

**Comment by neenjaw** [comment]
I'm going to close this PR as it will be succeeded by #334

**Pull request closed without merging**
