### PR TITLE
`https` instead of `http`

### PR DESCRIPTION
**Pull request by NhanAZ**
I realized that some links are still using `http` protocol.
There are 28 links using `https` in 26 files and there are 10 links using `http` in 10 files.
This causes async? and `http` is not secure so I edited the whole link using `http` protocol to `https`.

### CODE REVIEW

**Comment by NhanAZ** [comment]
I just edited wikipedia's links. There are many other links that still use `http` but I'm not sure so I've ignored them.

**Comment by NhanAZ** [comment]
If required I will edit the rest of the links.

**Comment by neenjaw** [comment]
:+1: Would strongly recommend automating this process: `find ./exercises -type f -print0 | xargs -0 sed -i 's/http:\/\//https:\/\//g'`

**Comment by NhanAZ** [comment]
What about links that require `http`?

**Comment by neenjaw** [comment]
Do you have an example link that requires `http`?

**Comment by NhanAZ** [comment]
Local links :thinking:

**Comment by neenjaw** [comment]
When I run `grep -r -e 'http:\/\/'` I don't see any links that cannot be converted.  Am I missing something?

**Comment by NhanAZ** [comment]
I mean some local links require http instead of https
It's still a bit risky to switch all http to https
Anyway, most browsers automatically convert http to https

**Comment by neenjaw** [comment]
ah, yes, I understand now.  Yes, if there was a local web server interface that we referenced, yes it would require it to remain `http`.

**Review by neenjaw — APPROVED** [review]

**Comment by NhanAZ** [comment]
Great it's merged, thanks for the review PR. Wish you a good day!

**Pull request merged**
