### PR TITLE
fix: typos

### PR DESCRIPTION
**Pull request by vnkmpf**

### CODE REVIEW

**Comment by vnkmpf** [comment]
I thought the problem was with a slash in branch name. But it errs again. Yet, the same branch name worked for dstockto :/

**Comment by neenjaw** [comment]
yea, I think this is related to an action i added to this repo. I'm pretty sure this is safe to merge, but I don't have time to merge right now and monitor/correct, etc.  I will merge this tonight

**Comment by vnkmpf** [comment]
Thank you :)

**Comment by neenjaw** [comment]
I was hoping to get to this before vacation, I'm back next week, so won't make any commitment to merging before then, but I will see what I can do.

**Review by neenjaw — APPROVED** [review]

**Comment by neenjaw** [comment]
@vnkmpf I am going to merge this now. Sorry for the delay.  I found the reason the ci was failing:
1) It doesn't support committing the changed files to a forked repository
2) When you made your type fixes to the main concept file, it was trying to regenerate the typo from the source concept since those are templated files.  I have updated the template and source concept file

**Comment by vnkmpf** [comment]
No problem, it was no hotfix :)
Thank you for merging.

**Pull request merged**
