### PR TITLE
Add Darts exercise to PHP track

### PR DESCRIPTION
**Pull request by MichaelBunker**
Added the Darts exercise to the PHP track.

# Dart Instructions

Write a function that returns the earned points in a single toss of a Darts game.

[Darts](https://en.wikipedia.org/wiki/Darts) is a game where players throw darts to a [target](https://en.wikipedia.org/wiki/Darts#/media/File:Darts_in_a_dartboard.jpg).

In our particular instance of the game, the target rewards with 4 different amounts of points, depending on where the dart lands:

* If the dart lands outside the target, player earns no points (0 points).
* If the dart lands in the outer circle of the target, player earns 1 point.
* If the dart lands in the middle circle of the target, player earns 5 points.
* If the dart lands in the inner circle of the target, player earns 10 points.

Write a function that given a point in the target (defined by its `real` cartesian coordinates `x` and `y`), returns the correct amount earned by a dart landing in that point.

### CODE REVIEW

**Comment by MichaelBunker** [comment]
The failures for linting don't seem to be coming from my changes.


>Run composer lint:check
>./vendor/bin/phpcs --standard=phpcs-php.xml ./exercises
> file: D:\a\php\php\exercises\practice\hello-world\.meta\example.php
> file: D:\a\php\php\exercises\practice\hello-world\HelloWorld.php

**Comment by MichaelBunker** [comment]
Looks like the linting errors are coming from the changes made here https://github.com/exercism/php/pull/387

> There are some linting errors involved due to the strict checking not being in the source file. Ideally I'd not have anything else in this file. Is there an easy way to skip the linting for this exercise (or at least the strict checking bit)?

**Comment by neenjaw** [comment]
#392 should fix the linting problem

**Comment by neenjaw** [comment]
Your additions look great, I'd like to merge #392 first, then if we can rebase on that to get the linting working for you to make sure that we aren't missing anything, that would be good.

**Review by neenjaw — APPROVED** [review]
Nice work.  Merge plan: following #392's merge, rebase/merge main, then re-run CI

**Comment by MichaelBunker** [comment]
> 
> 
> Nice work. Merge plan: following #392's merge, rebase/merge main, then re-run CI

Rebase complete. Linter checks are passing.

**Pull request merged**
