### PR TITLE
#48in24: secret-handshake 

### PR DESCRIPTION
**Pull request by fejan-malek**
https://github.com/exercism/php/issues/733

 Change: Added only `@testdox`

### CODE REVIEW

**Comment by mk-mxp** [comment]
@fejan-malek Please re-run `configlet sync` command and rebase this branch.

**Comment by fejan-malek** [comment]
Running `configlet sync` gives me all the warning messages and info about missing test cases and instructions.

No changes appear.

**Comment by mk-mxp** [comment]
Please update your fork's `main` branch and rebase this branch. There were CI changes, and this branch does not use those as it is too old.

Thank you!

**Review by mk-mxp — COMMENTED** [review]
Thanks for this contribution!

**Pull request merged**
