### PR TITLE
#48in24: kindergarten-garden

### PR DESCRIPTION
**Pull request by fejan-malek**
https://github.com/exercism/php/issues/735

Changes have been made to this pull request
 - Added `testdox` and no new test case is added.
 - Change: Defined `const` for `diagram` repeating value in test cases.

### CODE REVIEW

**Comment by mk-mxp** [comment]
Same with this one: 2024-07-30 minus 2 weeks = 2024-07-16. On 2024-07-16 (or some days after) please re-run the `configlet` sync command and rebase this branch.

**Review by mk-mxp — CHANGES_REQUESTED** [review]
Despite having an [ongoing discussion](http://forum.exercism.org/t/bug-in-golang-kindergarten-garden/8001/5) about the names in this exercise, I think we should get this sync'ed now.

As with the other exercises, please swap `@testdox` and `uuid`. `@testdox` must be last in the DocBlock comment.

Also I am not a friend of DRY'ed test methods here at exercism. The reason is: Students in the online editor see directly the code of the test method that fails. But with the constant they do not see the actual value of `self::DIAGRAM` in there. Which makes it unnecessarily complicated to understand what is happening. So please, put in again the duplicated string with the garden's diagram.

**Comment by fejan-malek** [comment]
> Same with this one: 2024-07-30 minus 2 weeks = 2024-07-16. On 2024-07-16 (or some days after) please re-run the `configlet` sync command and rebase this branch.

I hit `configlet` sync command but there was no difference.

**Comment by fejan-malek** [comment]
> So please, put in again the duplicated string with the garden's diagram.

What is the garden's diagram?

**Review by mk-mxp — APPROVED** [review]
Great! Thanks for your contribution.

**Comment by mk-mxp** [comment]
> > So please, put in again the duplicated string with the garden's diagram.
> 
> What is the garden's diagram?

They called the input string "garden's diagram" in the instructions.

**Pull request merged**
