### PR TITLE
Update INSTALLATION.md

### PR DESCRIPTION
**Pull request by pdmoore**
Add whitespace before link to windows download

### CODE REVIEW

**Comment by pdmoore** [comment]
yw - I don't have write access to this repo - can you merge for me?

**Comment by pdmoore** [comment]
@petemcfarlane [bump] - Are you able to merge this for me? I don't have write access here.

**Comment by petemcfarlane** [comment]
Sorry, I think I got distracted when I realised the build pipeline is broken. Once that is fixed I will merge this PR. Any help fixing that (the build pipeline!) would be greatly appreciated, if you're keen? It's kinda blocking PRs right now...

**Comment by pdmoore** [comment]
The error seems pretty straightforward; either demote phpUnit or upgrade php - I don't know enough about php versions to make the right call:

$ make test
running tests for: accumulate
**PHPUnit 9.0.1** by Sebastian Bergmann and contributors.
**This version of PHPUnit is supported on PHP 7.3, PHP 7.4, and PHP 8.**
**You are using PHP 7.2.15 (/home/travis/.phpenv/versions/7.2.15/bin/php).**
Makefile:40: recipe for target 'test-assignment' failed
make[1]: *** [test-assignment] Error 1
Makefile:46: recipe for target 'test' failed
make: *** [test] Error 1
The command "make test" exited with 2.

**Comment by petemcfarlane** [comment]
Ok, I've fixed the CI pipeline, please can you rebase from or merge master? Thank you for your patience

**Pull request closed without merging**
